// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/06/2025, 10:30:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/alexandre/Documentos/comandagoadmin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/plugins/**/*.{js,ts,mjs}","/home/alexandre/Documentos/comandagoadmin/composables/**/*.{js,ts,mjs}","/home/alexandre/Documentos/comandagoadmin/utils/**/*.{js,ts,mjs}","/home/alexandre/Documentos/comandagoadmin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/comandagoadmin/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;